version: "3"
services:

    postgres:
      image: postgres:9.5-alpine
      container_name: app-postgres
      volumes:
         - "db_data:/var/lib/postgresql/data"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
       - "5432:5432"

    webserver:
      image: nginx:alpine
      container_name: nginx-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./sourcefiles/nginx:/etc/nginx/conf.d
      ports:
       - "80:80"
      depends_on:
        - web-app

    web-app:
      build: sourcefiles/php-fpm
      container_name: app-lavarel
      working_dir: /application
      volumes:
        - ./application:/application
        - ./sourcefiles/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      depends_on:
        - postgres
volumes:
  db_data: